import type { PortfolioDataByLocale, ShowcaseProject } from '@/types/portfolio';
import { tc } from '@/utils/techColor';

const wpCoreTech = [tc('WordPress'), tc('PHP'), tc('HTML'), tc('JavaScript'), tc('jQuery'), tc('Sass'), tc('CSS'), tc('Bootstrap')];
const wpExtendedTech = [...wpCoreTech, tc('Lighthouse'), tc('Google Analytics')];

const translations = {
  en: {
    wpRole: 'Front End Developer – Freelancer',
    avonDesc: 'Built a custom WordPress theme for Avon\'s LMS training platform for new consultants. Developed responsive layouts for desktop and mobile with cross-browser compatibility.',
    avonProject: 'Avon – LMS Training Theme',
    complletaDesc: 'Created a custom WordPress theme for a design and architecture store. Developed responsive layouts and maintained plugins, security patches, and performance optimizations.',
    complletaProject: 'Complleta – E-commerce Theme',
    monterreDesc: 'Built a custom WordPress theme for a high-rise construction company. Developed responsive layouts and maintained plugins, security, and performance.',
    monterreProject: 'Monterre – Institutional Website',
    mooveDesc: 'Created a custom WordPress theme for a psychology clinic and career mentoring practice. Developed responsive layouts and maintained plugins, security, and performance.',
    mooveProject: 'Moove – Institutional Website',
    mrvDesc: 'Built a custom WordPress theme for one of Brazil\'s largest residential construction companies. Developed responsive layouts and maintained plugins, security, and performance.',
    mrvProject: 'MRV – Institutional Website',
    mvDesc: 'Created a custom WordPress theme for a metallic structures company. Developed responsive layouts and maintained plugins, security, and performance.',
    mvProject: 'MV Estruturas – Institutional Website',
    quiroDesc: 'Built a custom WordPress theme for a chiropractic clinic. Developed responsive layouts and maintained plugins, security, and performance.',
    quiroProject: 'Quiropraxia – Institutional Website',
    valeDesc: 'Created a custom WordPress theme for an architecture studio. Developed responsive layouts and maintained plugins, security, and performance.',
    valeProject: 'Vale Arquitetura – Institutional Website',
    vliDesc: 'Built a custom WordPress theme for one of Brazil\'s largest logistics companies. Developed responsive layouts and maintained plugins, security, and performance.',
    vliProject: 'VLI – Institutional Website',
    respMaintenance: 'Maintained WordPress plugins, applied security patches, and optimized site performance.',
    respTheme: 'Developed responsive themes for desktop and mobile with cross-browser compatibility.',
  },
  pt: {
    wpRole: 'Desenvolvedor Front End – Freelancer',
    avonDesc: 'Criação de tema WordPress personalizado para a plataforma LMS de treinamento da Avon para novos consultores. Layouts responsivos para desktop e mobile com compatibilidade cross-browser.',
    avonProject: 'Avon – Tema LMS de Treinamento',
    complletaDesc: 'Criação de tema WordPress personalizado para uma loja de design e arquitetura. Layouts responsivos e manutenção de plugins, segurança e performance.',
    complletaProject: 'Complleta – Tema E-commerce',
    monterreDesc: 'Criação de tema WordPress personalizado para construtora de alto padrão. Layouts responsivos e manutenção de plugins, segurança e performance.',
    monterreProject: 'Monterre – Site Institucional',
    mooveDesc: 'Criação de tema WordPress personalizado para clínica de psicologia e mentoria de carreira. Layouts responsivos e manutenção de plugins, segurança e performance.',
    mooveProject: 'Moove – Site Institucional',
    mrvDesc: 'Criação de tema WordPress personalizado para uma das maiores construtoras residenciais do Brasil. Layouts responsivos e manutenção de plugins, segurança e performance.',
    mrvProject: 'MRV – Site Institucional',
    mvDesc: 'Criação de tema WordPress personalizado para empresa de estruturas metálicas. Layouts responsivos e manutenção de plugins, segurança e performance.',
    mvProject: 'MV Estruturas – Site Institucional',
    quiroDesc: 'Criação de tema WordPress personalizado para clínica de quiropraxia. Layouts responsivos e manutenção de plugins, segurança e performance.',
    quiroProject: 'Quiropraxia – Site Institucional',
    valeDesc: 'Criação de tema WordPress personalizado para estúdio de arquitetura. Layouts responsivos e manutenção de plugins, segurança e performance.',
    valeProject: 'Vale Arquitetura – Site Institucional',
    vliDesc: 'Criação de tema WordPress personalizado para uma das maiores empresas de logística do Brasil. Layouts responsivos e manutenção de plugins, segurança e performance.',
    vliProject: 'VLI – Site Institucional',
    respMaintenance: 'Manutenção de plugins WordPress, aplicação de patches de segurança e otimização de performance.',
    respTheme: 'Desenvolvimento de temas responsivos para desktop e mobile com compatibilidade cross-browser.',
  },
  es: {
    wpRole: 'Desarrollador Front End – Freelancer',
    avonDesc: 'Creación de tema WordPress personalizado para la plataforma LMS de capacitación de Avon para nuevos consultores. Layouts responsivos para escritorio y móvil con compatibilidad cross-browser.',
    avonProject: 'Avon – Tema LMS de Capacitación',
    complletaDesc: 'Creación de tema WordPress personalizado para una tienda de diseño y arquitectura. Layouts responsivos y mantenimiento de plugins, seguridad y rendimiento.',
    complletaProject: 'Complleta – Tema E-commerce',
    monterreDesc: 'Creación de tema WordPress personalizado para constructora de alto nivel. Layouts responsivos y mantenimiento de plugins, seguridad y rendimiento.',
    monterreProject: 'Monterre – Sitio Institucional',
    mooveDesc: 'Creación de tema WordPress personalizado para clínica de psicología y mentoría de carrera. Layouts responsivos y mantenimiento de plugins, seguridad y rendimiento.',
    mooveProject: 'Moove – Sitio Institucional',
    mrvDesc: 'Creación de tema WordPress personalizado para una de las mayores constructoras residenciales de Brasil. Layouts responsivos y mantenimiento de plugins, seguridad y rendimiento.',
    mrvProject: 'MRV – Sitio Institucional',
    mvDesc: 'Creación de tema WordPress personalizado para empresa de estructuras metálicas. Layouts responsivos y mantenimiento de plugins, seguridad y rendimiento.',
    mvProject: 'MV Estructuras – Sitio Institucional',
    quiroDesc: 'Creación de tema WordPress personalizado para clínica de quiropráctica. Layouts responsivos y mantenimiento de plugins, seguridad y rendimiento.',
    quiroProject: 'Quiropraxia – Sitio Institucional',
    valeDesc: 'Creación de tema WordPress personalizado para estudio de arquitectura. Layouts responsivos y mantenimiento de plugins, seguridad y rendimiento.',
    valeProject: 'Vale Arquitectura – Sitio Institucional',
    vliDesc: 'Creación de tema WordPress personalizado para una de las mayores empresas de logística de Brasil. Layouts responsivos y mantenimiento de plugins, seguridad y rendimiento.',
    vliProject: 'VLI – Sitio Institucional',
    respMaintenance: 'Mantenimiento de plugins WordPress, aplicación de parches de seguridad y optimización de rendimiento.',
    respTheme: 'Desarrollo de temas responsivos para escritorio y móvil con compatibilidad cross-browser.',
  },
};

function buildShowcase(locale: 'en' | 'pt' | 'es'): ShowcaseProject[] {
  const t = translations[locale];

  return [
    {
      id: 'avon',
      name: 'Avon',
      image: '/images/portfolio/avon.png',
      url: 'https://www.avon.com.br',
      enabled: true,
      details: {
        id: 'avon',
        name: 'Avon',
        logoInitial: 'A',
        logoBg: '#FCE4EC',
        logoImage: '/images/portfolio/avon.png',
        url: 'https://www.avon.com.br',
        period: '2019',
        role: t.wpRole,
        responsibilities: [t.respTheme, t.respMaintenance],
        projects: [
          {
            name: t.avonProject,
            period: '2019',
            description: t.avonDesc,
            techStack: wpCoreTech,
          },
        ],
      },
    },
    {
      id: 'complleta',
      name: 'Complleta',
      image: '/images/portfolio/complleta.png',
      enabled: false,
      details: {
        id: 'complleta',
        name: 'Complleta',
        logoInitial: 'C',
        logoBg: '#E8EAF6',
        logoImage: '/images/portfolio/complleta.png',
        period: '2014',
        role: t.wpRole,
        responsibilities: [t.respTheme, t.respMaintenance],
        projects: [
          {
            name: t.complletaProject,
            period: '2014',
            description: t.complletaDesc,
            techStack: wpExtendedTech,
          },
        ],
      },
    },
    {
      id: 'monterre',
      name: 'Monterre',
      image: '/images/portfolio/monterre.png',
      url: 'https://www.monterre.com.br',
      enabled: true,
      details: {
        id: 'monterre',
        name: 'Monterre',
        logoInitial: 'M',
        logoBg: '#FFF3E0',
        logoImage: '/images/portfolio/monterre.png',
        url: 'https://www.monterre.com.br',
        period: '2018',
        role: t.wpRole,
        responsibilities: [t.respTheme, t.respMaintenance],
        projects: [
          {
            name: t.monterreProject,
            period: '2018',
            description: t.monterreDesc,
            techStack: wpExtendedTech,
          },
        ],
      },
    },
    {
      id: 'moove',
      name: 'Moove',
      image: '/images/portfolio/moove.png',
      url: 'https://moovedesenvolvimento.com.br',
      enabled: true,
      details: {
        id: 'moove',
        name: 'Moove',
        logoInitial: 'M',
        logoBg: '#E0F2F1',
        logoImage: '/images/portfolio/moove.png',
        url: 'https://moovedesenvolvimento.com.br',
        period: '2015',
        role: t.wpRole,
        responsibilities: [t.respTheme, t.respMaintenance],
        projects: [
          {
            name: t.mooveProject,
            period: '2015',
            description: t.mooveDesc,
            techStack: wpExtendedTech,
          },
        ],
      },
    },
    {
      id: 'mrv',
      name: 'MRV',
      image: '/images/portfolio/mrv.png',
      url: 'https://www.mrv.com.br',
      enabled: true,
      details: {
        id: 'mrv',
        name: 'MRV',
        logoInitial: 'M',
        logoBg: '#E8F5E9',
        logoImage: '/images/portfolio/mrv.png',
        url: 'https://www.mrv.com.br',
        period: '2019',
        role: t.wpRole,
        responsibilities: [t.respTheme, t.respMaintenance],
        projects: [
          {
            name: t.mrvProject,
            period: '2019',
            description: t.mrvDesc,
            techStack: wpExtendedTech,
          },
        ],
      },
    },
    {
      id: 'mv-estruturas',
      name: 'MV Estruturas',
      image: '/images/portfolio/mvestruturas.png',
      url: 'https://www.mvestruturas.com.br',
      enabled: false,
      details: {
        id: 'mv-estruturas',
        name: 'MV Estruturas',
        logoInitial: 'M',
        logoBg: '#EFEBE9',
        logoImage: '/images/portfolio/mvestruturas.png',
        period: '2017',
        role: t.wpRole,
        responsibilities: [t.respTheme, t.respMaintenance],
        projects: [
          {
            name: t.mvProject,
            period: '2017',
            description: t.mvDesc,
            techStack: wpExtendedTech,
          },
        ],
      },
    },
    {
      id: 'quiropraxia',
      name: 'Quiropraxia',
      image: '/images/portfolio/quiropraxia.png',
      url: 'https://www.quiropraxia.com.br',
      enabled: false,
      details: {
        id: 'quiropraxia',
        name: 'Quiropraxia',
        logoInitial: 'Q',
        logoBg: '#E3F2FD',
        logoImage: '/images/portfolio/quiropraxia.png',
        period: '2017',
        role: t.wpRole,
        responsibilities: [t.respTheme, t.respMaintenance],
        projects: [
          {
            name: t.quiroProject,
            period: '2017',
            description: t.quiroDesc,
            techStack: wpExtendedTech,
          },
        ],
      },
    },
    {
      id: 'vale-arquitetura',
      name: 'Vale Arquitetura',
      image: '/images/portfolio/vale.png',
      url: 'https://www.valearquitetura.com.br',
      enabled: false,
      details: {
        id: 'vale-arquitetura',
        name: 'Vale Arquitetura',
        logoInitial: 'V',
        logoBg: '#F3E5F5',
        logoImage: '/images/portfolio/vale.png',
        period: '2018',
        role: t.wpRole,
        responsibilities: [t.respTheme, t.respMaintenance],
        projects: [
          {
            name: t.valeProject,
            period: '2018',
            description: t.valeDesc,
            techStack: wpExtendedTech,
          },
        ],
      },
    },
    {
      id: 'vli',
      name: 'VLI',
      image: '/images/portfolio/vli.png',
      url: 'https://www.vli-logistica.com.br',
      enabled: true,
      details: {
        id: 'vli',
        name: 'VLI',
        logoInitial: 'V',
        logoBg: '#E8F5E9',
        logoImage: '/images/portfolio/vli.png',
        url: 'https://www.vli-logistica.com.br',
        period: '2019',
        role: t.wpRole,
        responsibilities: [t.respTheme, t.respMaintenance],
        projects: [
          {
            name: t.vliProject,
            period: '2019',
            description: t.vliDesc,
            techStack: wpExtendedTech,
          },
        ],
      },
    },
  ];
}

export const portfolioData: PortfolioDataByLocale = {
  en: buildShowcase('en'),
  pt: buildShowcase('pt'),
  es: buildShowcase('es'),
};
