import type { IconType } from 'react-icons';
import {
  SiFigma,
  SiCss,
  SiGit,
  SiTypescript,
  SiJavascript,
  SiAngular,
  SiSass,
  SiStorybook,
  SiGithubactions,
  SiTailwindcss,
  SiJest,
  SiReact,
  SiNodedotjs,
  SiDocker,
  SiRedux,
  SiGraphql,
  SiJenkins,
  SiMongodb,
  SiPostgresql,
  SiVuedotjs,
  SiJquery,
  SiGulp,
  SiDotnet,
  SiGitkraken,
  SiApachekafka,
  SiCypress,
  SiWordpress,
  SiPhp,
  SiHtml5,
  SiBootstrap,
  SiGoogleanalytics,
  SiLighthouse,
} from 'react-icons/si';
import { VscCode, VscServerProcess } from 'react-icons/vsc';
import { FaAws, FaJava, FaDatabase, FaCloud, FaMicrosoft } from 'react-icons/fa';

interface TechIconEntry {
  icon: IconType;
  color: string;
}

export const techIconMap: Record<string, TechIconEntry> = {
  Figma:            { icon: SiFigma,            color: '#F24E1E' },
  CSS:              { icon: SiCss,              color: '#264DE4' },
  Git:              { icon: SiGit,              color: '#F05032' },
  AWS:              { icon: FaAws,              color: '#FF9900' },
  Pipes:            { icon: SiApachekafka,      color: '#231F20' },
  CTS:              { icon: VscCode,            color: '#3178C6' },
  TypeScript:       { icon: SiTypescript,       color: '#3178C6' },
  Jasper:           { icon: FaDatabase,         color: '#CC0000' },
  JavaScript:       { icon: SiJavascript,       color: '#F7DF1E' },
  GitKraken:        { icon: SiGitkraken,        color: '#179287' },
  'React Front UI': { icon: SiReact,            color: '#61DAFB' },
  'CloudFront UI':  { icon: FaCloud,            color: '#FF9900' },
  Angular:          { icon: SiAngular,          color: '#DD0031' },
  Sass:             { icon: SiSass,             color: '#CC6699' },
  Storybook:        { icon: SiStorybook,        color: '#FF4785' },
  'GitHub Actions': { icon: SiGithubactions,    color: '#2088FF' },
  Microservices:    { icon: VscServerProcess,   color: '#6DB33F' },
  Microfrontends:   { icon: VscServerProcess,   color: '#6DB33F' },
  Tailwind:         { icon: SiTailwindcss,      color: '#06B6D4' },
  Jest:             { icon: SiJest,             color: '#C21325' },
  'Node.js':        { icon: SiNodedotjs,        color: '#339933' },
  Docker:           { icon: SiDocker,           color: '#2496ED' },
  Redux:            { icon: SiRedux,            color: '#764ABC' },
  GraphQL:          { icon: SiGraphql,          color: '#E10098' },
  'CI/CD':          { icon: SiGithubactions,    color: '#4CAF50' },
  Jenkins:          { icon: SiJenkins,          color: '#D24939' },
  MongoDB:          { icon: SiMongodb,          color: '#47A248' },
  PostgreSQL:       { icon: SiPostgresql,       color: '#4169E1' },
  Vue:              { icon: SiVuedotjs,         color: '#4FC08D' },
  React:            { icon: SiReact,            color: '#61DAFB' },
  Gulp:             { icon: SiGulp,             color: '#CF4647' },
  jQuery:           { icon: SiJquery,           color: '#0769AD' },
  Java:             { icon: FaJava,             color: '#ED8B00' },
  '.NET':           { icon: SiDotnet,           color: '#512BD4' },
  SQL:              { icon: FaDatabase,         color: '#336791' },
  Cypress:          { icon: SiCypress,          color: '#69D3A7' },
  Azure:            { icon: FaMicrosoft,        color: '#0078D4' },
  Githbub:          { icon: SiGit,              color: '#181717' },
  WordPress:        { icon: SiWordpress,        color: '#21759B' },
  PHP:              { icon: SiPhp,              color: '#777BB4' },
  HTML:             { icon: SiHtml5,            color: '#E34F26' },
  Bootstrap:        { icon: SiBootstrap,        color: '#7952B3' },
  'Google Analytics': { icon: SiGoogleanalytics, color: '#E37400' },
  Lighthouse:       { icon: SiLighthouse,       color: '#F44B21' },
};
